package webf.hibernate.db;
// Generated 08.04.2015 11:42:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Kurse generated by hbm2java
 */
public class Kurse  implements java.io.Serializable {


     private Integer kursePk;
     private String beschreibung;
     private Set persons = new HashSet(0);

    public Kurse() {
    }

	
    public Kurse(String beschreibung) {
        this.beschreibung = beschreibung;
    }
    public Kurse(String beschreibung, Set persons) {
       this.beschreibung = beschreibung;
       this.persons = persons;
    }
   
    public Integer getKursePk() {
        return this.kursePk;
    }
    
    public void setKursePk(Integer kursePk) {
        this.kursePk = kursePk;
    }
    public String getBeschreibung() {
        return this.beschreibung;
    }
    
    public void setBeschreibung(String beschreibung) {
        this.beschreibung = beschreibung;
    }
    public Set getPersons() {
        return this.persons;
    }
    
    public void setPersons(Set persons) {
        this.persons = persons;
    }




}


