package webf.hibernate.db;
// Generated 07.01.2016 21:47:34 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Person generated by hbm2java
 */
public class Person  implements java.io.Serializable {


     private Integer personPk;
     private Role role;
     private String username;
     private String password;
     private String firstname;
     private String lastname;
     private Date birthday;
     private Set courses = new HashSet(0);
     private Set personCourseMemberships = new HashSet(0);

    public Person() {
    }

	
    public Person(String username, String password) {
        this.username = username;
        this.password = password;
    }
    public Person(Role role, String username, String password, String firstname, String lastname, Date birthday, Set courses, Set personCourseMemberships) {
       this.role = role;
       this.username = username;
       this.password = password;
       this.firstname = firstname;
       this.lastname = lastname;
       this.birthday = birthday;
       this.courses = courses;
       this.personCourseMemberships = personCourseMemberships;
    }
   
    public Integer getPersonPk() {
        return this.personPk;
    }
    
    public void setPersonPk(Integer personPk) {
        this.personPk = personPk;
    }
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public Set getCourses() {
        return this.courses;
    }
    
    public void setCourses(Set courses) {
        this.courses = courses;
    }
    public Set getPersonCourseMemberships() {
        return this.personCourseMemberships;
    }
    
    public void setPersonCourseMemberships(Set personCourseMemberships) {
        this.personCourseMemberships = personCourseMemberships;
    }




}


