package webf.hibernate.db;
// Generated 01.12.2015 18:38:26 by Hibernate Tools 4.3.1



/**
 * PersonCourseMembershipId generated by hbm2java
 */
public class PersonCourseMembershipId  implements java.io.Serializable {


     private int personFk;
     private int courseFk;

    public PersonCourseMembershipId() {
    }

    public PersonCourseMembershipId(int personFk, int courseFk) {
       this.personFk = personFk;
       this.courseFk = courseFk;
    }
   
    public int getPersonFk() {
        return this.personFk;
    }
    
    public void setPersonFk(int personFk) {
        this.personFk = personFk;
    }
    public int getCourseFk() {
        return this.courseFk;
    }
    
    public void setCourseFk(int courseFk) {
        this.courseFk = courseFk;
    }




}


